"""empty message

Revision ID: 26093776d2c4
Revises: 
Create Date: 2022-07-05 13:41:51.051426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26093776d2c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('comment', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_post_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'post')
    op.drop_column('comment', 'username')
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('thumbnail', sa.String(length=100), nullable=False))
    op.add_column('post', sa.Column('caption', sa.String(length=200), nullable=True))
    op.add_column('post', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'post', ['thumbnail'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'dislikes')
    op.drop_column('post', 'likes')
    op.add_column('user', sa.Column('dp', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'user', ['dp'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'dp')
    op.add_column('post', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='unique')
    op.drop_column('post', 'date_created')
    op.drop_column('post', 'caption')
    op.drop_column('post', 'thumbnail')
    op.drop_column('post', 'user_id')
    op.add_column('comment', sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('comment', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_post_fkey', 'comment', 'post', ['post'], ['id'])
    op.drop_column('comment', 'post_id')
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###
